In [3674]:
import numpy as np

# Creamos nuestro Primer Array

In [3676]:
arr = np.array([10,20,98,34])

# Observamos el tipo de clase que tiene un array

In [3678]:
print(type(arr))

<class 'numpy.ndarray'>


In [3679]:
mi_tupla = (1,58,63,45)
print(type(mi_tupla))

arr_tuple = np.array(mi_tupla)
print(arr_tuple)
print(type(arr_tuple))

<class 'tuple'>
[ 1 58 63 45]
<class 'numpy.ndarray'>


In [3680]:
my_dict = {
    'one': 'uno',
    'two': 'dos',
    'three': 'tres'
}
dict_list = list(my_dict.items())
print(dict_list)

arr_dict = np.array(dict_list)
print(arr_dict)

[('one', 'uno'), ('two', 'dos'), ('three', 'tres')]
[['one' 'uno']
 ['two' 'dos']
 ['three' 'tres']]


In [3681]:
a = np.array(42)
print(a.ndim)

0


In [3682]:
b = np.array([1,2,3,4,5])
print(b.ndim)

1


In [3683]:
c = np.array([
    [1,2,3], [4,5,6]
])
print(c.ndim)

2


In [3684]:
d = np.array([
    [[1,2,3],[1,2,3]],
    [[1,2,3],[1,2,3]]
])
print(d.ndim)

3


In [3685]:
e = np.array([
    [
        [[1,2,3], [4,5,6]],
        [[1,2,3], [4,5,6]],
        [[1,2,3], [4,5,6]],
        [[1,2,3], [4,5,6]]
    ]
])
print(e.ndim)

4


### No tiene dimensiones, solamente el número 42

In [3687]:
print(a.shape)

()


### Longitud 5 dimensión 1

In [3689]:
print(b.shape)

(5,)


### Longitud 2, cada lista tiene 3 elementos.

In [3691]:
print(c.shape)

(2, 3)


### Longitud 2, cada sub-lista tiene 2 listas, de 3 elementos

In [3693]:
print(d.shape)

(2, 2, 3)


### Longitud 1, dentro hay 4 sub-listas, cada sub-lista tiene 2 listas de 3 elementos

In [3695]:
print(e.shape)

(1, 4, 2, 3)


In [3696]:
my_array = np.arange(11)

In [3697]:
my_array[0:3] # De posición 0 a 3

array([0, 1, 2])

In [3698]:
my_array[2:7] # De posición 2 a 7

array([2, 3, 4, 5, 6])

In [3699]:
my_array[:6] # De inicio a 6

array([0, 1, 2, 3, 4, 5])

In [3700]:
my_array[6:] # De 6 a final

array([ 6,  7,  8,  9, 10])

In [3701]:
my_array[:9:3] # De inicio a 9 de tres en tres elementos

array([0, 3, 6])

In [3702]:
my_array[6::2] # De 6 a fin de dos en dos elementos

array([ 6,  8, 10])

In [3703]:
my_array[-2] # Posición 2 empezando por el final

9

In [3704]:
my_array[:-3] # De inicio hasta el elemento -3 del array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [3705]:
my_array[::-1] # Array reverso

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [3706]:
my_array[::-2] # De fin (reverso) a inicio tomados de 2 en 2

array([10,  8,  6,  4,  2,  0])

In [3707]:
new_array = np.arange(36).reshape(2,3,6)
new_array

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [3708]:
basic_array = np.arange(3).reshape(1,3)
basic_array

array([[0, 1, 2]])

In [3709]:
new_dims = e.reshape(2,2,6)
new_dims

array([[[1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]],

       [[1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]]])

In [3710]:
new_dims.ravel()

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4,
       5, 6])

In [3711]:
new_dims.flatten()

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4,
       5, 6])

In [3712]:
pares = np.array([

    [0, 2, 4],

    [6, 8, 10],

    [12, 14, 16]

])

impares = np.array([

    [1, 3, 5],

    [7, 9, 11],

    [13, 15, 17]

])

### Apila los arrays en referencia a la la longitud 3

In [3714]:
np.hstack((pares, impares)) 

array([[ 0,  2,  4,  1,  3,  5],
       [ 6,  8, 10,  7,  9, 11],
       [12, 14, 16, 13, 15, 17]])

### Apila los arrays en referencia al número de elementos.

In [3716]:
np.vstack((pares, impares)) 

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [3717]:
np.concatenate((pares,impares), axis=1)

array([[ 0,  2,  4,  1,  3,  5],
       [ 6,  8, 10,  7,  9, 11],
       [12, 14, 16, 13, 15, 17]])

In [3718]:
np.concatenate((pares,impares), axis=0)

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [3719]:
np.dstack((pares,impares))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

### Dividir (spliting) arrays

In [3721]:
np.hsplit(pares,3)

[array([[ 0],
        [ 6],
        [12]]),
 array([[ 2],
        [ 8],
        [14]]),
 array([[ 4],
        [10],
        [16]])]

In [3722]:
np.vsplit(pares, 3)

[array([[0, 2, 4]]), array([[ 6,  8, 10]]), array([[12, 14, 16]])]

In [3723]:
np.split(pares, 3, axis=1)
np.split(pares, 3, axis=0)

[array([[0, 2, 4]]), array([[ 6,  8, 10]]), array([[12, 14, 16]])]

In [3724]:
big = np.arange(27).reshape(3,3,3)
big

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [3725]:
np.dsplit(big,3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]),
 array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]),
 array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

### Atributos de un array

In [3727]:
big.ndim

3

In [3728]:
big.size

27

In [3729]:
big.itemsize

4

In [3730]:
big.nbytes

108

In [3731]:
big.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

### Convertir arrays

In [3733]:
lista = big.tolist()

In [3734]:
print(lista)
print(type(lista))

[[[0, 1, 2], [3, 4, 5], [6, 7, 8]], [[9, 10, 11], [12, 13, 14], [15, 16, 17]], [[18, 19, 20], [21, 22, 23], [24, 25, 26]]]
<class 'list'>


In [3735]:
big.astype(float)

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]],

       [[ 9., 10., 11.],
        [12., 13., 14.],
        [15., 16., 17.]],

       [[18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.]]])

In [3736]:
big.astype(str)

array([[['0', '1', '2'],
        ['3', '4', '5'],
        ['6', '7', '8']],

       [['9', '10', '11'],
        ['12', '13', '14'],
        ['15', '16', '17']],

       [['18', '19', '20'],
        ['21', '22', '23'],
        ['24', '25', '26']]], dtype='<U11')

### Definimos un array con elementos del 2 hasta 20

In [3738]:
arr = np.arange(2, 20)
print(arr)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


### Asignamos las dos últimas posiciones a la variable b

In [3740]:
b = arr[-2:]
print(b)

[18 19]


### Asignamos todas las posiciones del array b a cero.

In [3742]:
b[::] = 0
print(b)

[0 0]


### Los cambios se reflejan en nuestra variable arr

In [3744]:
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,  0,
        0])

### Otro ejemplo

In [3746]:
array_dos = np.arange(0, 31)
print(array_dos)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]


In [3747]:
c = array_dos[0:5]
print(c)

[0 1 2 3 4]


In [3748]:
c[::] = 100
print(c)

[100 100 100 100 100]


In [3749]:
array_dos

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30])

### Ejemplo con función view(I)

In [3751]:
array_uno = np.array([[10,10], [2,3], [4,5]]) 
print(array_uno)

[[10 10]
 [ 2  3]
 [ 4  5]]


In [3752]:
array_dos = array_uno.view()
print(array_dos)

[[10 10]
 [ 2  3]
 [ 4  5]]


In [3753]:
array_dos[0] = [10000, 3]
print(array_dos)
print(array_uno)

[[10000     3]
 [    2     3]
 [    4     5]]
[[10000     3]
 [    2     3]
 [    4     5]]


### Ejemplo con función view(II)

In [3755]:
id(array_uno)
id(array_dos)

2145787811024

In [3756]:
array_dos[0] = [1000,3]
print(array_dos)

[[1000    3]
 [   2    3]
 [   4    5]]


### Ejemplo con función copy

In [3758]:
array_copiado = array_uno.copy()
print(id(array_uno))
print(id(array_copiado))

2145787426448
2145788207312


In [3759]:
array_uno = [2200, 34]
print(array_uno)
print(array_copiado)

[2200, 34]
[[1000    3]
 [   2    3]
 [   4    5]]


### Suma de todo el array o por sus ejes

In [3761]:
e = np.array([[[1, 0], [0, 0]],
              [[1, 1], [1, 0]],
              [[1, 0], [0, 1]]])
e.sum(axis=0)

array([[3, 1],
       [1, 1]])

In [3762]:
e.sum(axis=1)

array([[1, 0],
       [2, 1],
       [1, 1]])

### Generar un array con valores inicializados para ser rellenados posteriormente empty

In [3764]:
nothing = np.empty(10)
print(nothing)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


### Generar un array de ceros o unos

In [3766]:
ones = np.ones(5)
print(ones)

[1. 1. 1. 1. 1.]


In [3767]:
zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


### Generar Números Aleatorios

In [3769]:
rand = np.random.rand(10)
print(rand)

[0.64697997 0.63351387 0.2067981  0.66732492 0.57446829 0.39963607
 0.60929059 0.35643728 0.85638328 0.66543236]


In [3770]:
randn = np.random.randn(10)
print(randn)

[-1.92571501  0.53723662  1.34756918 -0.64190539  0.5092749   0.97540738
 -1.18901636 -0.54851543  0.69170848 -0.14452521]


In [3771]:
randint = np.random.randint(20,100,10)
print(randint)

[58 75 32 87 86 68 54 44 84 23]


In [3772]:
random = np.random.random(10)
print(random)

[0.44891591 0.88080663 0.96150356 0.2115504  0.83042145 0.04135716
 0.77032177 0.38718578 0.22928994 0.92424924]


In [3773]:
beta = np.random.beta(0.2, 0.5, 10)
print(beta)

[9.27822741e-03 1.07379133e-02 5.23827442e-01 3.99355214e-03
 4.69839784e-01 4.37733229e-01 1.60712955e-03 5.06706727e-06
 1.27289329e-01 5.71417655e-03]


In [3774]:
gamma = np.random.gamma(0.25, 0.3, 10)
print(gamma)

[2.58419958e-01 9.67863003e-02 3.95948684e-01 3.23531753e-03
 3.79768011e-01 5.74563705e-06 3.74637823e-03 4.39051861e-03
 2.30916544e-02 2.13827991e-07]


In [3775]:
binomial = np.random.binomial(10, 0.5, 10)
print(binomial)

[8 2 6 6 2 9 6 7 3 5]


### Redondear todos los elementos de un array round

In [3777]:
gamma.round(2)

array([0.26, 0.1 , 0.4 , 0.  , 0.38, 0.  , 0.  , 0.  , 0.02, 0.  ])

### Rellenar n elemenetos de un array fill.

In [3779]:
zero_array = np.zeros(20)
zero_array[5:15].fill(5)
print(zero_array)

[0. 0. 0. 0. 0. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 0. 0. 0. 0. 0.]


### Media del array o por sus ejes mean

In [3781]:
e.mean(axis = 0)

array([[1.        , 0.33333333],
       [0.33333333, 0.33333333]])

In [3782]:
e.mean(axis = 1)

array([[0.5, 0. ],
       [1. , 0.5],
       [0.5, 0.5]])

In [3783]:
e.mean()

0.5

### Producto de un array

In [3785]:
e.dot(d)

array([[[[1, 2, 3],
         [1, 2, 3]],

        [[0, 0, 0],
         [0, 0, 0]]],


       [[[2, 4, 6],
         [2, 4, 6]],

        [[1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]]])

### Valor mínimo de un array min

In [3787]:
aux = np.array([
    [1, 100, 5],
    [2, 4, 0]
])

In [3788]:
aux.min()

0

In [3789]:
aux.min(axis=0)

array([1, 4, 0])

In [3790]:
aux.min(axis=1)

array([1, 0])

### Valor máximo de un array max

In [3792]:
print(aux.max())

100


In [3793]:
print(aux.max(axis=0))

[  2 100   5]


In [3794]:
print(aux.max(axis=0))

[  2 100   5]


### Posición de índice con el valor mínimo de un array "argmin"

In [3796]:
aux.argmin()

5

### Posición de índice con el valor máximo de un array "argmax"

In [3798]:
aux.argmax()

1

### Ordenar valores de un array sort

In [3897]:
aux.sort()
aux

array([[  1,   5, 100],
       [  0,   2,   4]])